Scraping javascript generated HTML web pages

see
https://goo.gl/R9qfE8
https://github.com/rogerjdeangelis/utl_scrape_javascript_converting_table_to_sas_dataset_no_browser

see
https://goo.gl/AZwWkq
https://stackoverflow.com/questions/47596587/how-to-extract-id-names-from-search-result-urls-using-rvest-css-selector-isnt

Scraping javascript generated HTML web pages

Javascript loaded html pages are much more difficult to scrape.
The HTML is not static but is generated by a Javascript.

You may want to close your web browser.


HAVE  A javascript generated web page
=====================================

https://fantasy.premierleague.com/a/entry/767830/history

You see scripts instead of static HTML.

<script type="text/javascript" src="https://ismdj.scdn5.secure.raxcdn.com/static/CACHE/js/9a1e7ec0cf22.js"></script>

Here is what the javascript generated HTML looks like


                GPGAMEWEEK_       PBPOINTS_     GRGAMEWEEK_   OPOVERALL_      OROVERALL_
 GWGAMEWEEK          POINTS        ON_BENCH            RANK       POINTS            RANK    _VALUE

    GW1                  34               1       2,406,373           34       2,406,373    £100.0
    GW2                  47               6       2,659,789           81       2,448,674    £100.0
    GW3                  53               9         541,258          134       1,914,025    £99.9
    GW4                  51               7         905,524          185       1,461,665    £100.0
    GW5                  66              14         379,438          247         958,889    £100.1
    GW6                  66               2         303,704          309         510,376    £99.9
    GW7                  65               9         138,792          370         232,474    £99.8
    GW8                  63               3         108,363          433          87,967    £100.4
    GW9                  48               8       1,114,609          481          75,385    £100.9
    GW10                 90               2          71,210          571          27,716    £101.1
    GW11                 71               2         421,706          638          16,083    £100.9
    GW12                 35               9       2,798,661          669          31,820    £101.2
 ...

WANT  (SAS dataset slightly abreviated)
===================

Up to 40 obs from wantdf total obs=20


                   GAMEWEEK_    POINTS_    GAMEWEEK_      OVERALL_    OVERALL_
Obs    GAMEWEEK      POINTS      BENCH       RANK          POINTS     RANK          VALUE

  1      GW1           34           1      2,406,373       34         2,406,373    Â£100.0
  2      GW2           47           6      2,659,789       81         2,448,674    Â£100.0
  3      GW3           53           9      541,258         134        1,914,025    Â£99.9
  4      GW4           51           7      905,524         185        1,461,665    Â£100.0
  5      GW5           66          14      379,438         247        958,889      Â£100.1
  6      GW6           66           2      303,704         309        510,376      Â£99.9
  7      GW7           65           9      138,792         370        232,474      Â£99.8
  8      GW8           63           3      108,363         433        87,967       Â£100.4
  9      GW9           48           8      1,114,609       481        75,385       Â£100.9
 10      GW10          90           2      71,210          571        27,716       Â£101.1
 11      GW11          71           2      421,706         638        16,083       Â£100.9
 12      GW12          35           9      2,798,661       669        31,820       Â£101.2
 13      GW13          41           8      2,738,535       710        53,487       Â£101.1
 14      GW14          82          15      308,725         792        29,436       Â£100.2
 15      GW15          55           9      1,048,808       843        29,399       Â£100.6
 16      GW16          49           8      1,801,549       892        35,142       Â£100.7
 17      GW17          48           4      2,116,706       940        40,857       Â£100.7
 18      GW18          42           2      3,315,031       982        78,136       Â£100.8
 19      GW19          41           9      2,600,618       1,023      99,048       Â£100.6
 20      GW20          53           0      1,644,385       1,076      113,148      Â£100.8


SOLUTION
========

%utl_submit_wps64('
libname sd1 "d:/sd1";
options set=R_HOME "C:/Program Files/R/R-3.2.4";
libname wrk "%sysfunc(pathname(work))";
proc r;
submit;
library(RSelenium);
library(rvest);
psPath <- "C:/phantomjs-2.1.1-windows/bin/phantomjs.exe";
ptm <- phantom(psPath);
rd <- remoteDriver(browserName = "phantomjs");
rd$open();
rd$navigate("https://fantasy.premierleague.com/a/entry/767830/history");
Sys.sleep(1);
html <- rd$getPageSource()[[1]];
rd$close();
ptm$stop();
df <- html %>% read_html() %>%
    html_node("#ismr-event-history table.ism-table") %>%
    html_table() %>%
    setNames(gsub("\\S+\\s+(\\S+)", "\\1", names(.))) %>%
    setNames(gsub("\\s", "_", names(.)));
str(df);
endsubmit;
import r=df data=wrk.wantdf;
run;quit;
');

Up to 40 obs from wantdf total obs=20
1                                        The WPS System      14:42 Friday, January  6, 2017

NOTE: (c) Copyright World Programming Limited 2002-2016.  All rights reserved.
NOTE: World Programming System 3.02 (03.02.02.00.015680)
      Licensed to Roger DeAngelis, for express only
NOTE: This session is executing on the X64_WIN7PRO platform and is running in 64 bit mode

NOTE: This session is executing in WPS EXPRESS edition mode and is limited to processing only
      100 records from any input dataset or file.

NOTE: AUTOEXEC processing beginning; file is c:\oto\Tut_Otowps.sas
NOTE: Format num2mis output
NOTE: Format $chr2mis output
NOTE: Procedure format step took :
      real time : 0.015
      cpu time  : 0.015



NOTE: The data step took :
      real time : 0.000
      cpu time  : 0.000


NOTE: AUTOEXEC processing completed

1         libname sd1 "d:/sd1";
NOTE: Library sd1 assigned as follows:
      Engine:        SAS7BDAT
      Physical Name: d:\sd1

2         options set=R_HOME "C:/Program Files/R/R-3.2.4";
3         libname wrk "e:\saswork\wrk\_TD3964_BEAST_";
NOTE: Library wrk assigned as follows:
      Engine:        SAS7BDAT
      Physical Name: e:\saswork\wrk\_TD3964_BEAST_

4         proc r;
5         submit;
6         library(RSelenium);
7         library(rvest);
8         psPath <- "C:/phantomjs-2.1.1-windows/bin/phantomjs.exe";
9         ptm <- phantom(psPath);
10        rd <- remoteDriver(browserName = "phantomjs");
11        rd$open();
12        rd$navigate("https://fantasy.premierleague.com/a/entry/767830/history");
13        Sys.sleep(1);
14        html <- rd$getPageSource()[[1]];
15        rd$close();
16        ptm$stop();
17        df <- html %>% read_html() %>%
html_node("#ismr-event-history table.ism-table") %>%
html_table() %>%
setNames(gsub("\\S+\\s+(\\S+)", "\\1", names(.))) %
17      ! >%    setNames(gsub("\\s", "_", names(.)));
18        str(df);
19        endsubmit;
NOTE: Using R version 3.2.4 Revised (2016-03-16 r70336) from C:/Program Files/R/R-3.2.4

NOTE: Submitting statements to R:

> library(RSelenium);
Warning message:
package 'RSelenium' was built under R version 3.2.5
> library(rvest);
Loading required package: xml2
Warning messages:


Up to 40 obs from wantdf total obs=20
1: package 'rvest' was built under R version 3.2.5

2                                                                             The WPS System


2: package 'xml2' was built under R version 3.2.5
> psPath <- "C:/phantomjs-2.1.1-windows/bin/phantomjs.exe";
> ptm <- phantom(psPath);
> rd <- remoteDriver(browserName = "phantomjs");
> rd$open();
> rd$navigate("https://fantasy.premierleague.com/a/entry/767830/history");
> Sys.sleep(1);
> html <- rd$getPageSource()[[1]];
> rd$close();
> ptm$stop();
> df <- html %>% read_html() %>%    html_node("#ismr-event-history table.ism-table") %>%
html_table() %>%    setNames(gsub("\\S+\\s+(\\S+)", "\\1", names(.))) %>%
setNames(gsub("\\s", "_", names(.)));
> str(df);

'data.frame':      20 obs. of  10 variables:
 $ Gameweek                : chr  "GW1" "GW2" "GW3" "GW4" ...
 $ Gameweek_Points         : int  34 47 53 51 66 66 65 63 48 90 ...
 $ Points_Bench            : int  1 6 9 7 14 2 9 3 8 2 ...
 $ Gameweek_Rank           : chr  "2,406,373" "2,659,789" "541,258" "905,524" ...
 $ Transfers_Made          : int  0 0 2 0 3 2 2 0 2 0 ...
 $ Transfers_Cost          : int  0 0 0 0 4 4 4 0 0 0 ...
 $ Overall_Points          : chr  "34" "81" "134" "185" ...
 $ Overall_Rank            : chr  "2,406,373" "2,448,674" "1,914,025" "1,461,665" ...
 $ Value                   : chr  "£100.0" "£100.0" "£99.9" "£100.0" ...
 $ Change_Previous_Gameweek: logi  NA NA NA NA NA NA ...

NOTE: Processing of R statements complete

20        import r=df data=wrk.wantdf;
NOTE: Creating data set 'WRK.wantdf' from R data frame 'df'
NOTE: Column names modified during import of 'df'
NOTE: Data set "WRK.wantdf" has 20 observation(s) and 10 variable(s)

21        run;
NOTE: Procedure r step took :
      real time : 6.970
      cpu time  : 0.031


22        quit;

NOTE: Submitted statements took :
      real time : 7.002
      cpu time  : 0.062

